variables:
  IMAGE_NAME: "logstash/logstash-jdbc-input-plugin"

building-image:
  stage: deploy
  before_script:
    - 'docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD $DOCKER_REGISTRY_HOSTED'
    - 'docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD $DOCKER_REGISTRY_PUBLIC'
  script:
    - 'docker build -t $IMAGE_NAME:$CI_COMMIT_TAG .'
    - 'docker tag $IMAGE_NAME:$CI_COMMIT_TAG $DOCKER_REGISTRY_HOSTED/$IMAGE_NAME:$CI_COMMIT_TAG'
    - 'docker push $DOCKER_REGISTRY_HOSTED/$IMAGE_NAME:$CI_COMMIT_TAG'
  only:
    - /-final$/
